{"name": "test_invalid_auth", "status": "passed", "start": 1758723798455, "stop": 1758723798640, "uuid": "1a211c77-273d-499e-ab57-18120c3c8823", "historyId": "7063f0cc1670ef7e4a4ad5b5efff06a4", "testCaseId": "7063f0cc1670ef7e4a4ad5b5efff06a4", "fullName": "tests.test_scenario_auth.TestAuthScenario#test_invalid_auth", "labels": [{"name": "tag", "value": "ready"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_scenario_auth"}, {"name": "subSuite", "value": "TestAuthScenario"}, {"name": "host", "value": "WIN-VIK827QHRC6"}, {"name": "thread", "value": "8092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_scenario_auth"}], "titlePath": ["tests", "test_scenario_auth.py", "TestAuthScenario"]}